// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

#region Namespace Using

using System.Reflection;
using System.Resources;

#endregion

[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Rigsarkivet")]
[assembly: AssemblyCulture("")]

[assembly: AssemblyProduct("ADA")]
[assembly: AssemblyCopyright("Copyright � Statens Arkiver 2010-2017")]
[assembly: AssemblyTrademark("")]

[assembly: AssemblyVersion("3.4.7")]

[assembly: AssemblyFileVersion("3.4.7.1")] // Last number likely changed in jenkins, use UpdateBuildVersion.ps1


[assembly: NeutralResourcesLanguage("en")]