//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ra.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ra.Common.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lowerCorner.
        /// </summary>
        internal static string BoundsLowerCornerName {
            get {
                return ResourceManager.GetString("BoundsLowerCornerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upperCorner.
        /// </summary>
        internal static string BoundsUpperCornerName {
            get {
                return ResourceManager.GetString("BoundsUpperCornerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to srsName.
        /// </summary>
        internal static string DatumName {
            get {
                return ResourceManager.GetString("DatumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to srsDimension.
        /// </summary>
        internal static string DimensionName {
            get {
                return ResourceManager.GetString("DimensionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelope.
        /// </summary>
        internal static string EnvelopeName {
            get {
                return ResourceManager.GetString("EnvelopeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.opengis.net/gml.
        /// </summary>
        internal static string OpenGisNs {
            get {
                return ResourceManager.GetString("OpenGisNs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.opengis.net/gml/3.1.1/base/gml.xsd.
        /// </summary>
        internal static string OpenGisSchemaLocation {
            get {
                return ResourceManager.GetString("OpenGisSchemaLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schemaLocation.
        /// </summary>
        internal static string SchemaLocationName {
            get {
                return ResourceManager.GetString("SchemaLocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.w3.org/1999/xlink.
        /// </summary>
        internal static string XlinkNs {
            get {
                return ResourceManager.GetString("XlinkNs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.w3.org/2001/XMLSchema-instance.
        /// </summary>
        internal static string XsiNs {
            get {
                return ResourceManager.GetString("XsiNs", resourceCulture);
            }
        }
    }
}
