//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ada.UI.Wpf.Text.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ada.UI.Wpf.Text.Properties.UIText", typeof(UIText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check All.
        /// </summary>
        public static string CheckAll {
            get {
                return ResourceManager.GetString("CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string CheckTreeItemStatus_Error {
            get {
                return ResourceManager.GetString("CheckTreeItemStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string CheckTreeItemStatus_Finished {
            get {
                return ResourceManager.GetString("CheckTreeItemStatus_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Containing info.
        /// </summary>
        public static string CheckTreeItemStatus_Info {
            get {
                return ResourceManager.GetString("CheckTreeItemStatus_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string CheckTreeItemStatus_Running {
            get {
                return ResourceManager.GetString("CheckTreeItemStatus_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        public static string CheckTreeItemStatus_Skipped {
            get {
                return ResourceManager.GetString("CheckTreeItemStatus_Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not run.
        /// </summary>
        public static string CheckTreeItemStatus_ToBeDone {
            get {
                return ResourceManager.GetString("CheckTreeItemStatus_ToBeDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check not recognized.
        /// </summary>
        public static string CheckTreeItemStatus_Unknown {
            get {
                return ResourceManager.GetString("CheckTreeItemStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected result?.
        /// </summary>
        public static string CheckTreeItemStatus_Warning {
            get {
                return ResourceManager.GetString("CheckTreeItemStatus_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cX.
        /// </summary>
        public static string ColumnId {
            get {
                return ResourceManager.GetString("ColumnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolonnenavn.
        /// </summary>
        public static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column filter.
        /// </summary>
        public static string ColumnsFilter {
            get {
                return ResourceManager.GetString("ColumnsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string ColumnsFilterEnum_All {
            get {
                return ResourceManager.GetString("ColumnsFilterEnum_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ColumnsFilterEnum_None {
            get {
                return ResourceManager.GetString("ColumnsFilterEnum_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary and foreign keys.
        /// </summary>
        public static string ColumnsFilterEnum_PrimaryAndForeignKeys {
            get {
                return ResourceManager.GetString("ColumnsFilterEnum_PrimaryAndForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary keys.
        /// </summary>
        public static string ColumnsFilterEnum_PrimaryKeys {
            get {
                return ResourceManager.GetString("ColumnsFilterEnum_PrimaryKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databases.
        /// </summary>
        public static string Databases {
            get {
                return ResourceManager.GetString("Databases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaultværdi.
        /// </summary>
        public static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete created databases and exit Ada.
        /// </summary>
        public static string DeleteCurrent {
            get {
                return ResourceManager.GetString("DeleteCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete databases.
        /// </summary>
        public static string DeleteDatabases {
            get {
                return ResourceManager.GetString("DeleteDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting workspace databases.
        /// </summary>
        public static string DeleteDatabasesTitle {
            get {
                return ResourceManager.GetString("DeleteDatabasesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slet.
        /// </summary>
        public static string DeleteGraphTable {
            get {
                return ResourceManager.GetString("DeleteGraphTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kant udlægning.
        /// </summary>
        public static string EdgeRoutingAlgorithm {
            get {
                return ResourceManager.GetString("EdgeRoutingAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundling.
        /// </summary>
        public static string EdgeRoutingEnum_Bundling {
            get {
                return ResourceManager.GetString("EdgeRoutingEnum_Bundling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen.
        /// </summary>
        public static string EdgeRoutingEnum_None {
            get {
                return ResourceManager.GetString("EdgeRoutingEnum_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Finder.
        /// </summary>
        public static string EdgeRoutingEnum_PathFinder {
            get {
                return ResourceManager.GetString("EdgeRoutingEnum_PathFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simpel.
        /// </summary>
        public static string EdgeRoutingEnum_SimpleER {
            get {
                return ResourceManager.GetString("EdgeRoutingEnum_SimpleER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ER Diagram.
        /// </summary>
        public static string ERGraph {
            get {
                return ResourceManager.GetString("ERGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut: ctrl+enter or F5.
        /// </summary>
        public static string ExecuteToolTip {
            get {
                return ResourceManager.GetString("ExecuteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find relationer.
        /// </summary>
        public static string FindPaths {
            get {
                return ResourceManager.GetString("FindPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mappe.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow reference.
        /// </summary>
        public static string FollowReference {
            get {
                return ResourceManager.GetString("FollowReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fremmednøglenavn.
        /// </summary>
        public static string ForeignKeyName {
            get {
                return ResourceManager.GetString("ForeignKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolonnefunktion.
        /// </summary>
        public static string FunctionalDescription {
            get {
                return ResourceManager.GetString("FunctionalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afleveret.
        /// </summary>
        public static string FunctionalDescriptionEnum_Afleveret {
            get {
                return ResourceManager.GetString("FunctionalDescriptionEnum_Afleveret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afsender modtager.
        /// </summary>
        public static string FunctionalDescriptionEnum_Afsender_modtager {
            get {
                return ResourceManager.GetString("FunctionalDescriptionEnum_Afsender_modtager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital signatur.
        /// </summary>
        public static string FunctionalDescriptionEnum_Digital_signatur {
            get {
                return ResourceManager.GetString("FunctionalDescriptionEnum_Digital_signatur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumentdato.
        /// </summary>
        public static string FunctionalDescriptionEnum_Dokumentdato {
            get {
                return ResourceManager.GetString("FunctionalDescriptionEnum_Dokumentdato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumentidentifikation.
        /// </summary>
        public static string FunctionalDescriptionEnum_Dokumentidentifikation {
            get {
                return ResourceManager.GetString("FunctionalDescriptionEnum_Dokumentidentifikation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumenttitel.
        /// </summary>
        public static string FunctionalDescriptionEnum_Dokumenttitel {
            get {
                return ResourceManager.GetString("FunctionalDescriptionEnum_Dokumenttitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORM.
        /// </summary>
        public static string FunctionalDescriptionEnum_FORM {
            get {
                return ResourceManager.GetString("FunctionalDescriptionEnum_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kassation.
        /// </summary>
        public static string FunctionalDescriptionEnum_Kassation {
            get {
                return ResourceManager.GetString("FunctionalDescriptionEnum_Kassation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagringsform.
        /// </summary>
        public static string FunctionalDescriptionEnum_Lagringsform {
            get {
                return ResourceManager.GetString("FunctionalDescriptionEnum_Lagringsform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myndighedsidentifikation.
        /// </summary>
        public static string FunctionalDescriptionEnum_Myndighedsidentifikation {
            get {
                return ResourceManager.GetString("FunctionalDescriptionEnum_Myndighedsidentifikation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sagsidentifikation.
        /// </summary>
        public static string FunctionalDescriptionEnum_Sagsidentifikation {
            get {
                return ResourceManager.GetString("FunctionalDescriptionEnum_Sagsidentifikation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sagstitel.
        /// </summary>
        public static string FunctionalDescriptionEnum_Sagstitel {
            get {
                return ResourceManager.GetString("FunctionalDescriptionEnum_Sagstitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolonnefunktion(er).
        /// </summary>
        public static string FunctionalDescriptions {
            get {
                return ResourceManager.GetString("FunctionalDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edges.
        /// </summary>
        public static string GraphControlEnum_Edge {
            get {
                return ResourceManager.GetString("GraphControlEnum_Edge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertexes.
        /// </summary>
        public static string GraphControlEnum_Vertex {
            get {
                return ResourceManager.GetString("GraphControlEnum_Vertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertexes and edges.
        /// </summary>
        public static string GraphControlEnum_VertexAndEdge {
            get {
                return ResourceManager.GetString("GraphControlEnum_VertexAndEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string HeaderLayout {
            get {
                return ResourceManager.GetString("HeaderLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visuals.
        /// </summary>
        public static string HeaderVisuals {
            get {
                return ResourceManager.GetString("HeaderVisuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlighted components.
        /// </summary>
        public static string HighLightedComponents {
            get {
                return ResourceManager.GetString("HighLightedComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlighted edges.
        /// </summary>
        public static string HighlightedEdges {
            get {
                return ResourceManager.GetString("HighlightedEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In and out.
        /// </summary>
        public static string HighlightEdgesEnum_All {
            get {
                return ResourceManager.GetString("HighlightEdgesEnum_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string HighlightEdgesEnum_In {
            get {
                return ResourceManager.GetString("HighlightEdgesEnum_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        public static string HighlightEdgesEnum_Out {
            get {
                return ResourceManager.GetString("HighlightEdgesEnum_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlighting.
        /// </summary>
        public static string HighlightEnabled {
            get {
                return ResourceManager.GetString("HighlightEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align edge labels.
        /// </summary>
        public static string IsEdgeLabelAligned {
            get {
                return ResourceManager.GetString("IsEdgeLabelAligned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show labels.
        /// </summary>
        public static string IsEdgeLabelsShown {
            get {
                return ResourceManager.GetString("IsEdgeLabelsShown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary key.
        /// </summary>
        public static string IsPrimaryKey {
            get {
                return ResourceManager.GetString("IsPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string LayoutAlgorithm {
            get {
                return ResourceManager.GetString("LayoutAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bounded FR.
        /// </summary>
        public static string LayoutEnum_BoundedFR {
            get {
                return ResourceManager.GetString("LayoutEnum_BoundedFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular.
        /// </summary>
        public static string LayoutEnum_Circular {
            get {
                return ResourceManager.GetString("LayoutEnum_Circular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound FDP.
        /// </summary>
        public static string LayoutEnum_CompoundFDP {
            get {
                return ResourceManager.GetString("LayoutEnum_CompoundFDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficient Sugiyama.
        /// </summary>
        public static string LayoutEnum_EfficientSugiyama {
            get {
                return ResourceManager.GetString("LayoutEnum_EfficientSugiyama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FR (Fruchterman-Reingold).
        /// </summary>
        public static string LayoutEnum_FR {
            get {
                return ResourceManager.GetString("LayoutEnum_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISOM.
        /// </summary>
        public static string LayoutEnum_ISOM {
            get {
                return ResourceManager.GetString("LayoutEnum_ISOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KK.
        /// </summary>
        public static string LayoutEnum_KK {
            get {
                return ResourceManager.GetString("LayoutEnum_KK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lin Log.
        /// </summary>
        public static string LayoutEnum_LinLog {
            get {
                return ResourceManager.GetString("LayoutEnum_LinLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Random.
        /// </summary>
        public static string LayoutEnum_SimpleRandom {
            get {
                return ResourceManager.GetString("LayoutEnum_SimpleRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugiyama.
        /// </summary>
        public static string LayoutEnum_Sugiyama {
            get {
                return ResourceManager.GetString("LayoutEnum_Sugiyama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree.
        /// </summary>
        public static string LayoutEnum_Tree {
            get {
                return ResourceManager.GetString("LayoutEnum_Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List results.
        /// </summary>
        public static string ListResults {
            get {
                return ResourceManager.GetString("ListResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainWindow.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max rows reached.
        /// </summary>
        public static string MaxRowsReached {
            get {
                return ResourceManager.GetString("MaxRowsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names.
        /// </summary>
        public static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New empty graf.
        /// </summary>
        public static string NewEmptyGraph {
            get {
                return ResourceManager.GetString("NewEmptyGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New full graf.
        /// </summary>
        public static string NewFullGraph {
            get {
                return ResourceManager.GetString("NewFullGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nej.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen forslag tilgængelige.
        /// </summary>
        public static string NoSuggestions {
            get {
                return ResourceManager.GetString("NoSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable.
        /// </summary>
        public static string Nullable {
            get {
                return ResourceManager.GetString("Nullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to af.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open AvId.
        /// </summary>
        public static string OpenAvId {
            get {
                return ResourceManager.GetString("OpenAvId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string OpenFolderSelection {
            get {
                return ResourceManager.GetString("OpenFolderSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSA.
        /// </summary>
        public static string OverlapRemovalEnum_FSA {
            get {
                return ResourceManager.GetString("OverlapRemovalEnum_FSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen.
        /// </summary>
        public static string OverlapRemovalEnum_None {
            get {
                return ResourceManager.GetString("OverlapRemovalEnum_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envejs FSA.
        /// </summary>
        public static string OverlapRemovalEnum_OneWayFSA {
            get {
                return ResourceManager.GetString("OverlapRemovalEnum_OneWayFSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjernelse af overlap.
        /// </summary>
        public static string OverlapRemovingAlgorithm {
            get {
                return ResourceManager.GetString("OverlapRemovingAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primærnøglenavn.
        /// </summary>
        public static string PrimaryKeyName {
            get {
                return ResourceManager.GetString("PrimaryKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forespørgsel.
        /// </summary>
        public static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beskrivelse.
        /// </summary>
        public static string QueryDescription {
            get {
                return ResourceManager.GetString("QueryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoriter.
        /// </summary>
        public static string QueryFavorites {
            get {
                return ResourceManager.GetString("QueryFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fra aflevering.
        /// </summary>
        public static string QueryFromAV {
            get {
                return ResourceManager.GetString("QueryFromAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seneste.
        /// </summary>
        public static string QueryLatest {
            get {
                return ResourceManager.GetString("QueryLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn.
        /// </summary>
        public static string QueryName {
            get {
                return ResourceManager.GetString("QueryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redraw graph.
        /// </summary>
        public static string RedrawLayout {
            get {
                return ResourceManager.GetString("RedrawLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reference.
        /// </summary>
        public static string reference {
            get {
                return ResourceManager.GetString("reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to referenced.
        /// </summary>
        public static string referenced {
            get {
                return ResourceManager.GetString("referenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to referencedTable.
        /// </summary>
        public static string referencedTable {
            get {
                return ResourceManager.GetString("referencedTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove tables from graph.
        /// </summary>
        public static string RemoveItemsFromGraph {
            get {
                return ResourceManager.GetString("RemoveItemsFromGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        public static string Rows {
            get {
                return ResourceManager.GetString("Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start at row.
        /// </summary>
        public static string RowsStartAt {
            get {
                return ResourceManager.GetString("RowsStartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows to show.
        /// </summary>
        public static string RowsToShow {
            get {
                return ResourceManager.GetString("RowsToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run query.
        /// </summary>
        public static string RunAvQuery {
            get {
                return ResourceManager.GetString("RunAvQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run tests.
        /// </summary>
        public static string RunTest {
            get {
                return ResourceManager.GetString("RunTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query results.
        /// </summary>
        public static string RunTestQuery {
            get {
                return ResourceManager.GetString("RunTestQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marker forbundede.
        /// </summary>
        public static string SelectConnected {
            get {
                return ResourceManager.GetString("SelectConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected edges.
        /// </summary>
        public static string SelectedEdges {
            get {
                return ResourceManager.GetString("SelectedEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string SelectedEdgesEnum_All {
            get {
                return ResourceManager.GetString("SelectedEdgesEnum_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string SelectedEdgesEnum_In {
            get {
                return ResourceManager.GetString("SelectedEdgesEnum_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string SelectedEdgesEnum_None {
            get {
                return ResourceManager.GetString("SelectedEdgesEnum_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        public static string SelectedEdgesEnum_Out {
            get {
                return ResourceManager.GetString("SelectedEdgesEnum_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string SelectedRelationEnum_Any {
            get {
                return ResourceManager.GetString("SelectedRelationEnum_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neighbors.
        /// </summary>
        public static string SelectedRelationEnum_Neighbors {
            get {
                return ResourceManager.GetString("SelectedRelationEnum_Neighbors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neighbors (in).
        /// </summary>
        public static string SelectedRelationEnum_NeighborsIn {
            get {
                return ResourceManager.GetString("SelectedRelationEnum_NeighborsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neighbors (out).
        /// </summary>
        public static string SelectedRelationEnum_NeighborsOut {
            get {
                return ResourceManager.GetString("SelectedRelationEnum_NeighborsOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only selected.
        /// </summary>
        public static string SelectedRelationEnum_Only {
            get {
                return ResourceManager.GetString("SelectedRelationEnum_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relations vs selected.
        /// </summary>
        public static string SelectedRelations {
            get {
                return ResourceManager.GetString("SelectedRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string SetValue {
            get {
                return ResourceManager.GetString("SetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string SeverityType {
            get {
                return ResourceManager.GetString("SeverityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string SeverityTypeError {
            get {
                return ResourceManager.GetString("SeverityTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string SeverityTypeInfo {
            get {
                return ResourceManager.GetString("SeverityTypeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show In Properties Window.
        /// </summary>
        public static string ShowInPropertiesWindow {
            get {
                return ResourceManager.GetString("ShowInPropertiesWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show as query.
        /// </summary>
        public static string ShowInQueryTable {
            get {
                return ResourceManager.GetString("ShowInQueryTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show report.
        /// </summary>
        public static string ShowReport {
            get {
                return ResourceManager.GetString("ShowReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ctrl+space for table and column suggestions.
        /// </summary>
        public static string SQLQueryTooltip {
            get {
                return ResourceManager.GetString("SQLQueryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabel name.
        /// </summary>
        public static string Tablename {
            get {
                return ResourceManager.GetString("Tablename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabel viewer.
        /// </summary>
        public static string TableViewer {
            get {
                return ResourceManager.GetString("TableViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture graph.
        /// </summary>
        public static string TakeScreenShot {
            get {
                return ResourceManager.GetString("TakeScreenShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To CSV.
        /// </summary>
        public static string ToCsv {
            get {
                return ResourceManager.GetString("ToCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original type.
        /// </summary>
        public static string TypeOriginal {
            get {
                return ResourceManager.GetString("TypeOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete all files..
        /// </summary>
        public static string UnableToDelete {
            get {
                return ResourceManager.GetString("UnableToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateDrives {
            get {
                return ResourceManager.GetString("UpdateDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth edges.
        /// </summary>
        public static string UseCurves {
            get {
                return ResourceManager.GetString("UseCurves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About to delete working databases for:.
        /// </summary>
        public static string WillDelete {
            get {
                return ResourceManager.GetString("WillDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About to delete working databases for:
        ///{0} ({1}).
        /// </summary>
        public static string WillDeleteF {
            get {
                return ResourceManager.GetString("WillDeleteF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
