//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ada.UI.Wpf.TableIndexViewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int SimultaneousSQLItemsShownMax {
            get {
                return ((int)(this["SimultaneousSQLItemsShownMax"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Ada.UI.Wpf.TableIndexViewer.DataTableViewer.Model.QueryList LatestQueries {
            get {
                return ((global::Ada.UI.Wpf.TableIndexViewer.DataTableViewer.Model.QueryList)(this["LatestQueries"]));
            }
            set {
                this["LatestQueries"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MaxLatestQueries {
            get {
                return ((int)(this["MaxLatestQueries"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Ada.UI.Wpf.TableIndexViewer.DataTableViewer.Model.QueryList FavoriteQueries {
            get {
                return ((global::Ada.UI.Wpf.TableIndexViewer.DataTableViewer.Model.QueryList)(this["FavoriteQueries"]));
            }
            set {
                this["FavoriteQueries"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int SimultaneousSQLItemsShownDefault {
            get {
                return ((int)(this["SimultaneousSQLItemsShownDefault"]));
            }
        }
    }
}
